SAD/urls.py
from django.contrib import admin
from django.urls import path, include

# Importa la vista que renderiza primera_vista.html
from bienvenido import views as bienvenido_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # Ruta raíz → primera_vista
    # Al ir a http://127.0.0.1:8000/ cargará primera_vista.html
    path('', bienvenido_views.primera_vista, name='primera_vista'),
    
    # Aquí incluimos todas las URLs que empiecen con /accounts/
    path('accounts/', include('usuarios.urls', namespace='usuarios')),
    
    # Ahora montamos la app "bienvenido" en /bienvenido/
    path('bienvenido/', include('bienvenido.urls', namespace='bienvenido')),
    
    # App “doctores” en /doctores/
    path('doctores/', include('doctores.urls', namespace='doctores')),
    
    # App “administradores” en /administradores/
    path('administradores/', include('administradores.urls', namespace='administradores')),
    

    # Si luego agregas otras apps, las incluirías igual:
    # path('citas/', include('citas.urls', namespace='citas')),
    # path('pacientes/', include('pacientes.urls', namespace='pacientes')),
    # etc.
]

administradores/urls.py
# doctores/urls.py

from django.urls import path
from . import views

app_name = 'administradores'

urlpatterns = [
    # Al acceder a /doctores/ (prefijo definido en SAD/urls.py), Django llamará a views.index
    path('', views.index, name='index'),
    path('inventario-registrar/', views.inventario_registrar, name='inventario-registrar'),
    path('inventario-alertas/', views.inventario_alertas, name='inventario-alertas'),
    path('proveedores-registrar/', views.proveedores_registrar, name='proveedores-registrar'),

]

administradores/models.py
from django.db import models

# Create your models here.

administradores/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'administradores/index.html')

def inventario_registrar(request):
    return render(request, 'administradores/inventario_registrar.html')

def inventario_alertas(request):
    return render(request, 'administradores/inventario_alertas.html')

def proveedores_registrar(request):
    return render(request, 'administradores/proveedor_registrar.html')

administradores/templates/administradores/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Administración</title>
  <link rel="stylesheet" href="{% static 'administradores/css/estilos.css' %}" />
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet" />
</head>
<body>
  <div class="container">
    <!-- Panel izquierdo -->
    <div class="left-panel">
      <nav class="navbar">
        <a href="#">Home</a>
        <a href="#">Testimonios</a>
        <a href="#">Dentistas</a>
        <a href="#">Sobre nosotros</a>
      </nav>

      <div class="info-usuario">
        <h1><span class="titulo-ovalado2">Bienvenido al SAD</span></h1>
        <img id="welcome-avatar" src="{% static 'bienvenido/img/default.png' %}" alt="Avatar">
        <p>Administrador</p>
      </div>

      <ul class="menu">
        <li><a href="{% url 'administradores:index' %}" target="_blank" rel="noopener noreferrer"><span class="icon">📅</span> Cita Médica</a></li>
        <li><a href="{% url 'administradores:inventario-registrar'%}" target="_blank" rel="noopener noreferrer"><span class="icon">📋</span> Inventario</a></li>
        <li><a href="{% url 'administradores:proveedores-registrar' %}" target="_blank"><span class="icon">🏬</span> Proveedores</a></li>
        <li><span class="icon">🔔</span> Recordatorios</li>
        <li><span class="icon">📈</span> Reporte</li>
        <li><span class="icon">👤</span> Perfil de Usuario</li>
        <li><span class="icon">👥</span> Colaboradores</li>
        <li><span class="icon">🛠️</span> Soporte</li>
        <li class="cerrar"><span class="icon">❌</span> Cerrar sesión</li>
      </ul>
    </div>

    <!-- Panel derecho -->
    <div class="right-panel">
      <div class="header">
        <h2><span class="titulo-ovalado">BIENVENIDO AL SAD</span></h2>
        <img src="{% static 'bienvenido/img/logoSAD.png' %}" alt="Logo SAD" class="logo"/>
      </div>

      <main class="main-content">
        <div class="menu-citas">
          <div class="menu-citas-header">Menú de Citas Médicas</div>
            <div class="menu-citas-opciones">
              <div class="opcion"><span class="icono">➕</span><span class="texto">Crear</span></div>
              <div class="opcion"><span class="icono">❌</span><span class="texto"><a href="{% url 'administradores:index' %}" target="_self">Cancelar</a></span></div>
              <div class="opcion"><span class="icono">🔄</span><span class="texto">Modificar</span></div>
            </div>
        </div>

        <div class="formulario-cita">
          <div class="perfil-contenedor-scrollable">
            <form class="formulario-historial">
              <h4 class="titulo-ovalado3">🆔 ID PACIENTE</h4>
              <input type="text" placeholder="Documento del paciente">

              <div class="boton-editar-container">
                <button class="btn-editar">Buscar</button>
              </div>

              <h4 class="titulo-ovalado3">📅 FECHA</h4>
              <input type="date" placeholder="Día cita" readonly>
              <h4 class="titulo-ovalado3">⏰ HORA</h4>
              <input type="time" placeholder="Hora cita" readonly>
              <h4 class="titulo-ovalado3">🦷 DENTISTA</h4>
              <input type="text" placeholder="Nombre del dentista" readonly>
              <h4 class="titulo-ovalado3">👁️ CITA</h4>
              <input type="text" placeholder="Tipo de cita" readonly>
            </form>
          </div>
        </div>

        <div class="boton-editar-container">
          <button class="btn-editar">Cancelar</button>
        </div>
      </main>
      <footer>
        © 2025 Sistema de Agendamiento Dental S.A.D. Todos los derechos reservados.
      </footer>
    </div>
  </div>
</body>
</html>

administradores/templates/administradores/inventario_alertas.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Inventario Alertas</title>
  <link rel="stylesheet" href="{% static 'administradores/css/inventario_alertas.css' %}" />
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet" />
</head>
<body>
  <div class="container">
    <!-- Panel izquierdo -->
    <div class="left-panel">
      <nav class="navbar">
        <a href="#">Home</a>
        <a href="#">Testimonios</a>
        <a href="#">Dentistas</a>
        <a href="#">Sobre nosotros</a>
      </nav>

      <div class="info-usuario">
        <h1><span class="titulo-ovalado2">Bienvenido al SAD</span></h1>
        <img id="welcome-avatar" src="{% static 'bienvenido/img/default.png' %}" alt="Avatar">
        <p>Administrador</p>
      </div>

      <ul class="menu">
        <li><a href="{% url 'administradores:index' %}" target="_blank" rel="noopener noreferrer"><span class="icon">📅</span> Cita Médica</a></li>
        <li><a href="{% url 'administradores:inventario-registrar'%}" target="_blank" rel="noopener noreferrer"><span class="icon">📋</span> Inventario</a></li>
        <li><a href="{% url 'administradores:proveedores-registrar' %}" target="_blank"><span class="icon">🏬</span> Proveedores</a></li>
        <li><span class="icon">🔔</span> Recordatorios</li>
        <li><span class="icon">📈</span> Reporte</li>
        <li><span class="icon">👤</span> Perfil de Usuario</li>
        <li><span class="icon">👥</span> Colaboradores</li>
        <li><span class="icon">🛠️</span> Soporte</li>
        <li class="cerrar"><span class="icon">❌</span> Cerrar sesión</li>
      </ul>
    </div>

    <!-- Panel derecho -->
    <div class="right-panel">
      <div class="header">
        <h2><span class="titulo-ovalado">BIENVENIDO AL SAD</span></h2>
        <img src="{% static 'bienvenido/img/logoSAD.png' %}" alt="Logo SAD" class="logo"/>
      </div>

      <main class="main-content">
        <div class="menu-citas">
          <div class="menu-citas-header">Inventario</div>
            <div class="menu-citas-opciones">
              <div class="opcion"><span class="icono">📦</span><span class="texto"><a href="{% url 'administradores:inventario-registrar'%}" target="_self">Registrar</a></span></div>
              <div class="opcion"><span class="icono">🔍</span><span class="texto">Consultar</span></div>
              <div class="opcion"><span class="icono">⏰</span><span class="texto"><a href="{% url 'administradores:inventario-alertas' %}" target="_self">Alertas</span></a></div>
              <div class="opcion"><span class="icono">🔄</span><span class="texto">Actualizar</span></div>
            </div>
        </div>

        <div class="contenedor-reprogramar">
          <!-- Nueva Hora -->
          <h3 class="tituloovaladonegro2">ID Material</h3>
          <input type="text" class="input-reprogramar" value="ID Producto" readonly>
          <input type="text" class="input-reprogramar" value="ID Producto" readonly>
          <input type="text" class="input-reprogramar" value="ID Producto" readonly>
          <!-- Botón -->
          <button class="btn-reprogramar">Aceptar</button>
        </div>

      </main>
      <footer>
        © 2025 Sistema de Agendamiento Dental S.A.D. Todos los derechos reservados.
      </footer>
    </div>
  </div>
</body>
</html>

administradores/templates/administradores/inventario_registrar.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Inventario Registrar</title>
  <link rel="stylesheet" href="{% static 'administradores/css/inventario_registrar.css' %}" />
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet" />
</head>
<body>
  <div class="container">
    <!-- Panel izquierdo -->
    <div class="left-panel">
      <nav class="navbar">
        <a href="#">Home</a>
        <a href="#">Testimonios</a>
        <a href="#">Dentistas</a>
        <a href="#">Sobre nosotros</a>
      </nav>

      <div class="info-usuario">
        <h1><span class="titulo-ovalado2">Bienvenido al SAD</span></h1>
        <img id="welcome-avatar" src="{% static 'bienvenido/img/default.png' %}" alt="Avatar">
        <p>Administrador</p>
      </div>

      <ul class="menu">
        <li><a href="{% url 'administradores:index' %}" target="_blank" rel="noopener noreferrer"><span class="icon">📅</span> Cita Médica</a></li>
        <li><a href="{% url 'administradores:inventario-registrar'%}" target="_blank" rel="noopener noreferrer"><span class="icon">📋</span> Inventario</a></li>
        <li><a href="{% url 'administradores:proveedores-registrar' %}" target="_blank"><span class="icon">🏬</span> Proveedores</a></li>
        <li><span class="icon">🔔</span> Recordatorios</li>
        <li><span class="icon">📈</span> Reporte</li>
        <li><span class="icon">👤</span> Perfil de Usuario</li>
        <li><span class="icon">👥</span> Colaboradores</li>
        <li><span class="icon">🛠️</span> Soporte</li>
        <li class="cerrar"><span class="icon">❌</span> Cerrar sesión</li>
      </ul>
    </div>

    <!-- Panel derecho -->
    <div class="right-panel">
      <div class="header">
        <h2><span class="titulo-ovalado">BIENVENIDO AL SAD</span></h2>
        <img src="{% static 'bienvenido/img/logoSAD.png' %}" alt="Logo SAD" class="logo"/>
      </div>

      <main class="main-content">
        <div class="menu-citas">
          <div class="menu-citas-header">Inventario</div>
            <div class="menu-citas-opciones">
              <div class="opcion"><span class="icono">📦</span><span class="texto"><a href="{% url 'administradores:inventario-registrar'%}" target="_self">Registrar</a></span></div>
              <div class="opcion"><span class="icono">🔍</span><span class="texto">Consultar</span></div>
              <div class="opcion"><span class="icono">⏰</span><span class="texto"><a href="{% url 'administradores:inventario-alertas' %}" target="_self">Alertas</span></a></div>
              <div class="opcion"><span class="icono">🔄</span><span class="texto">Actualizar</span></div>
            </div>
        </div>

        <div class="contenedor-reprogramar">
          <!-- Nueva Hora -->
          <h3 class="tituloovaladonegro2">ID Material</h3>
          <input type="text" class="input-reprogramar" placeholder="ID Material">
          <!-- Nueva Fecha -->
          <h3 class="tituloovaladonegro1">Fecha de Registro</h3>
          <input type="date" class="input-reprogramar" placeholder="Día/Mes/Año">
          <!-- Nuevo Dentista -->
          <h3 class="tituloovaladonegro3">Proveedor</h3>
          <select class="input-reprogramar">
            <option disabled selected>Seleccione un proveedor</option>
            <option>Proveedor</option>
          </select>
          <!-- Botón Reprogramar -->
          <button class="btn-reprogramar">Registrar</button>
        </div>

      </main>
      <footer>
        © 2025 Sistema de Agendamiento Dental S.A.D. Todos los derechos reservados.
      </footer>
    </div>
  </div>
</body>
</html>

administradores/templates/administradores/proveedor_registrar.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Proveedores Registrar</title>
  <link rel="stylesheet" href="{% static 'administradores/css/proveedor_registrar.css' %}" />
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet" />
</head>
<body>
  <div class="container">
    <!-- Panel izquierdo -->
    <div class="left-panel">
      <nav class="navbar">
        <a href="#">Home</a>
        <a href="#">Testimonios</a>
        <a href="#">Dentistas</a>
        <a href="#">Sobre nosotros</a>
      </nav>

      <div class="info-usuario">
        <h1><span class="titulo-ovalado2">Bienvenido al SAD</span></h1>
        <img id="welcome-avatar" src="{% static 'bienvenido/img/default.png' %}" alt="Avatar">
        <p>Administrador</p>
      </div>

      <ul class="menu">
        <li><a href="{% url 'administradores:index' %}" target="_blank" rel="noopener noreferrer"><span class="icon">📅</span> Cita Médica</a></li>
        <li><a href="{% url 'administradores:inventario-registrar'%}" target="_blank" rel="noopener noreferrer"><span class="icon">📋</span> Inventario</a></li>
        <li><a href="{% url 'administradores:proveedores-registrar' %}" target="_blank"><span class="icon">🏬</span> Proveedores</a></li>
        <li><span class="icon">🔔</span> Recordatorios</li>
        <li><span class="icon">📈</span> Reporte</li>
        <li><span class="icon">👤</span> Perfil de Usuario</li>
        <li><span class="icon">👥</span> Colaboradores</li>
        <li><span class="icon">🛠️</span> Soporte</li>
        <li class="cerrar"><span class="icon">❌</span> Cerrar sesión</li>
      </ul>
    </div>

    <!-- Panel derecho -->
    <div class="right-panel">
      <div class="header">
        <h2><span class="titulo-ovalado">BIENVENIDO AL SAD</span></h2>
        <img src="{% static 'bienvenido/img/logoSAD.png' %}" alt="Logo SAD" class="logo"/>
      </div>

      <main class="main-content">
        <div class="menu-citas">
          <div class="menu-citas-header">Proveedor</div>
            <div class="menu-citas-opciones">
              <div class="opcion"><span class="icono">📦</span><span class="texto"><a href="{% url 'administradores:proveedores-registrar'}" target="_self">Registrar</a></span></div>
              <div class="opcion"><span class="icono">🔍</span><span class="texto">Consultar</span></div>
              <div class="opcion"><span class="icono">❌</span><span class="texto">Eliminar</span></div>
              <div class="opcion"><span class="icono">🔄</span><span class="texto">Actualizar</span></div>
            </div>
        </div>

            <div class="perfil-contenedor-scrollable">
              <form class="perfil-formulario">

                <h4 class="titulo-ovalado3">ID DEL PROVEEDOR</h4>
                <input type="text" placeholder="Identificación del Proveedor">

                <h4 class="titulo-ovalado3">NOMBRE DEL PROVEEDOR</h4>
                <input type="text" placeholder="Nombre(s) del Proveedor">

                <h4 class="titulo-ovalado3">CONTACTO PROVEEDOR</h4>
                <input type="text" placeholder="Contacto Proveedor">

                <h4 class="titulo-ovalado3">MATERIAL</h4>
                  <select class="input-reprogramar">
                    <option disabled selected>Seleccione el material</option>
                  </select>
              </form>
            </div>
            <!-- Botón -->
            <button class="btn-reprogramar">Registrar</button>
      </main>
      <footer>
        © 2025 Sistema de Agendamiento Dental S.A.D. Todos los derechos reservados.
      </footer>
    </div>
  </div>
</body>
</html>